#!/usr/bin/perl -w

#  Call after 'Stopfrsr'
#  Tars entire FRSR folder and stores in /home/rmr/frsrdata/ folder
#  
#  Call:  perl ArchiveFrsr
#  
#  Output: /home/rmr/frsrdata/frsrarchive_20151020T123456Z.tar.gz
# 

use lib $ENV{MYLIB};
use perltools::MRutilities;
use perltools::MRtime;

	## DATA PATH
my $datapath="$ENV{DAQPATH}/FRSR";
print"data path = $datapath\n";

	## ARCHIVE PATH
my $archivepath="$ENV{HOME}/frsrdata";
print"Archive path=$archivepath\n";
if(! -d $archivepath){
	print"Create $archivepath\n";
	`mkdir $archivepath`;
}

	## TAR FILE NAME
my $tarname=sprintf "frsrarchive_%s.tar.gz",dtstr(now(),'iso');
print"tarname=$tarname\n";


	## TAR COMMAND
my $cmd = sprintf "cd $datapath; tar -zcf $archivepath/$tarname .";
print"$cmd\n";
system $cmd;

exit 0;
