#!/usr/bin/perl -w

#  1. Call after 'Stopfrsr'
#  2. ArchiveFrsr
#
#  Wipes clean the FRSR/data folder
#    Asks permission before
#  
#  Call:  perl ClearFrsrData
#  
#  Output: none
# 

use lib $ENV{MYLIB};
use perltools::MRutilities;
use perltools::MRtime;

my $ans = 'n';
	## DATA PATH
my $datapath="$ENV{HomePath}/swmain/apps/FRSR/data";
	# COMMAND LINE
if($#ARGV >= 0 && $ARGV[0] =~ /y/i){
	$ans='y';
}else{
	print"
	=========================
	   WARNING
	=========================
	This process will delete everything from the FRSR/data folder.
	Command \"ArchiveFrsr\" should be used to backup all collected data.

	Proceed to delete?  (y or n): ";

	$ans=<>;
	chomp($ans);
	print"You entered $ans\n";
}
if($ans =~ /y/i){
	#print"Delete data\n";
	my $cmd="rm -r $datapath/*";
	#print"cmd=$cmd\n";
	system $cmd;
} else {
	print"No delete.\n";
}
exit 0;
