#!/usr/bin/perl -w

use lib $ENV{MYLIB};
use perltools::MRtime;
use perltools::MRutilities;

my @f = ('frsr');
my @v = ();

printf"NOW = %d\n",now();

	# SELECT STREAM
my ($is,$s,$cmd,$f,$age);

for($is=0; $is<=$#f; $is++){
	$f=$f[$is];
	#print"$f";
		# LAST RECORD TIME
	$cmd = sprintf("LastDataTime %s_raw",$f);
	$s = `$cmd`;
	chomp($s); 
	$s =~ s/^\s+//;
	$s =~ s/\s+$//;
	print"Last rec time = $s\n";

		# THE AGE OF THE RECORD
	if($s==0){
		print"    0 -- RECORD FAILURE.\n",$f;
		push @v,0;		
	} else {
		$age = now() - $s;
		print"age = $age\n";
		if ($age > 600){ print"    FAIL\n"; push @v,0}
		else{ print"    OK\n"; push @v, 1;  }
	}
}
my $good=1;
foreach(@v){if($_ == 0){$good=0}}
print"good = $good\n";
`echo $good > /tmp/tmpdaq`;

exit 0
