#! /usr/bin/perl -X

use lib "$ENV{MYLIB}";
use perltools::MRtime;
use perltools::MRutilities;

my ($pktlen,$cc,$packetid,$mode,$shadow,$shadowthreshold,$ix,$i,$hms,$dmy);
my (@g1,@g2,@sw);

$setupfile = $DAQSWFOLDER.'setup/su.txt';
$simflag=FindInfo($setupfile,'SIMULATEFLAG');
if($simflag == 1){
	printf"%d\n",now();
} else {
	my $recfile = '/tmp/lastrec';
		## PACKET FILE EXIST
	if ( -f $recfile ){
		$strin=`cat /tmp/lastrec`;
		$strin =~ s/^\s+//;
		$strin =~ s/\s+$//;
	}else{ 
		print"0\n"; exit 1;
	}

		## CHKSUM TEST
	$cc = NmeaChecksum( substr($strin,0,-2) );
	#printf"chksum=%s\n",substr($strin,-2);
	#printf"computed chksum=%s\n", $cc;
	if ($cc ne substr($strin,-2)) {
		print"0\n"; exit 1 }
	else {
			# TIME
		$i=index($strin,'<<');
		if($i < 0 ){print"0\n"; exit 1}
		else{
			$hms=substr($strin,$i+9,6);
			$i=index($strin,'>>');
			$dmy=substr($strin,$i-7,6);
			#print"$hms   $dmy\n";
			$dtgps=datesec(substr($dmy,4,2)+2000,substr($dmy,2,2),substr($dmy,0,2),substr($hms,0,2),substr($hms,2,2),substr($hms,4,2));
			printf"%d %s\n",$dtgps, dtstr($dtgps,'ssv');
		}
	}
}
exit 0;

#=========================================================
#$GPRMC,190824,A,4737.0000,S,12300.0000,W,002.1,202.0,210210,019.0,W*62
sub NmeaChecksum
# $cc = NmeaChecksum($str) where $str is the NMEA string that starts with '$' and ends with '*'.
{
    my ($line) = @_;
    my $csum = 0;
    $csum ^= unpack("C",(substr($line,$_,1))) for(1..length($line)-2);
    return (sprintf("%2.2X",$csum));
}
