#!/usr/bin/perl -X
#   ./LastAvg rad_avg (or 'gps_avg', 'wxt_raw', etc)

my (@a, $a, $cmd,$s);
$a = shift();
$cmd=sprintf"find %s -name $a* -print",$ENV{DAQDATAFOLDER};
@a=`$cmd`;
if($#a < 0){print"0"; exit 1}
$a=$a[$#a];
$s=`tail -1 $a`;
print"$s\n";
exit 0
