#!/usr/bin/expect --
# Make an Archive and continue data collection
set log_user 1

	# Spawn Stopfrsr,  expect "sw/$"
spawn KillScreen
expect "sw/$"
spawn Cleanupfrsr
expect "sw/$"

	# Spawn ArchiveFrsr, expect "sw/$"
spawn ArchiveFrsr
expect "sw/$"	

	# Spawn ClearFrsrData, expect "(y or n):"
spawn ClearFrsrData
	# Reply 'y'
expect "(y or n):"
send "y\r\n"
expect "sw/$"

	# start screen
set scrpid [spawn screen -S FRSR -c /Users/rmr/Dropbox/swmain/apps/FRSR/sw/tools/screenrc_frsr.txt]
send -i $scrpid "ls\r\n"
expect "sw/$"

puts "done"
exit 0
# 
# 	# Spawn Startfrsr, expect "sw/$"
# spawn screen {-S FRSR -p 2 -X stuff "G$(printf \\r)"}
# expect "sw/$"
# 	# end
