#! /usr/bin/perl
# edit 171025 simulate files are moved

use lib $ENV{MYLIB};
use perltools::MRtime;

$fin="$ENV{HOME}/frsrdata/simulate/frsr.txt";
# print"$fin\n";
# die;

my $irec = 0;
my ($i1,$narg,$p);

$narg = $#ARGV;
if($narg>=0){
	foreach(@ARGV){print"  $_\n"}
}

while (1) {
	$irec = 0;
	open(F,"<$fin") or die("fin error\n");

	# Loop through all the data records.
	while (<F>) {
		chomp( $str = $_);
		print"$str\r\n";
		sleep(1);
		if($str =~ /\$FSR03/){
			sleep(4);
			$irec++;
		}
	}
	print"Starting over\n";
	close F;
}
